# Generated by Django 5.0 on 2024-05-28 12:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_list', models.ManyToManyField(blank=True, related_name='follower_list', to=settings.AUTH_USER_MODEL)),
                ('following_list', models.ManyToManyField(blank=True, related_name='following_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
