# Generated by Django 5.0 on 2024-05-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='profile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
