# Generated by Django 5.0 on 2024-05-28 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_follow_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follower_list',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following_list',
        ),
        migrations.AddField(
            model_name='follow',
            name='follower_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='following_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
