# Generated by Django 5.0 on 2024-05-28 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_follow_follower_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='following_list',
        ),
        migrations.AddField(
            model_name='follow',
            name='following_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='following_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
