# Generated by Django 5.0 on 2024-06-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.CharField(default='https://i.pinimg.com/736x/0d/64/98/0d64989794b1a4c9d89bff571d3d5842.jpg', max_length=400),
        ),
    ]
