# Generated by Django 5.0 on 2024-06-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_alter_user_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
