# Generated by Django 5.0 on 2024-06-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.TextField(default='https://static.vecteezy.com/system/resources/thumbnails/009/292/244/small/default-avatar-icon-of-social-media-user-vector.jpg'),
        ),
    ]
